### ISSUE TITLE
Zero byte *.obj files for msvc 32-bit

### ISSUE THREAD

**Issue by gbluma** [OCamlPro/ocpwin-distrib#11]
In the latest 32-bit MSVC built binary, found at

http://www.ocamlpro.com/pub/ocpwin/ocpwin-builds/ocpwin32/ocpwin32-20151008-msvc32-4.01.0+ocp1.exe

Contains the following object files, which are (erroneously) empty:

flexdll_initer_msvc.obj
flexdll_msvc.obj
flexdll_ocaml_msvc.obj

This means that native libraries can't be linked via ocamlopt.exe. 

Also note, the previous builds appear to have this issue as well.

**Comment by lefessan** [comment]
This is fixed in 20151024 versions. Can anybody confirm ?
Note that you need to download a specific version of MSVC, for now, the "Windows SDK and .NET Framework 3.5" (not 4 !) to benefit from OCPWin MSVC auto-detection. Otherwise, you will need to configure your PATHs and other env variables for MSVC.

If you want to help us support a particular version of MSVC, you should send us the corresponding vcvars{32/64}.bat and other bat files from the same directory, in VisualStudio installation.
